# Generated by Django 4.2.8 on 2024-10-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_survey_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text_answer',
        ),
    ]
